import 'package:parki_dog/features/dog_owner/data/models/breed_model.dart';

List<Breed> breeds = [
  const Breed(id: '1', name: 'Affenpinscher'),
  const Breed(id: '2', name: 'Afghan Hound'),
  const Breed(id: '3', name: 'Airedale Terrier'),
  const Breed(id: '4', name: 'Akita'),
  const Breed(id: '5', name: 'Alaskan Malamute'),
  const Breed(id: '6', name: 'Alpine Dachsbracke'),
  const Breed(id: '7', name: 'American Akita'),
  const Breed(id: '8', name: 'American Cocker Spaniel'),
  const Breed(id: '9', name: 'American Foxhound'),
  const Breed(id: '10', name: 'American Staffordshire Terrier'),
  const Breed(id: '11', name: 'American Water Spaniel'),
  const Breed(id: '12', name: 'Appenzell Cattle'),
  const Breed(id: '14', name: 'Ariege Pointing Dog'),
  const Breed(id: '15', name: 'Ariegeois'),
  const Breed(id: '16', name: 'Artois Hound'),
  const Breed(id: '17', name: 'Atlas Mountain (Aidi)'),
  const Breed(id: '18', name: 'Australian Cattle Dog'),
  const Breed(id: '19', name: 'Australian Kelpie'),
  const Breed(id: '20', name: 'Australian Shepherd'),
  const Breed(id: '21', name: 'Australian Silky Terrier'),
  const Breed(id: '22', name: 'Australian Stumpy Tail Cattle Dog'),
  const Breed(id: '23', name: 'Australian Terrier'),
  const Breed(id: '24', name: 'Austrian  Pinscher'),
  const Breed(id: '25', name: 'Austrian Black And Tan Hound'),
  const Breed(id: '26', name: 'Auvergne Pointer'),
  const Breed(id: '27', name: 'Azawakh'),
  const Breed(id: '28', name: 'Basenji'),
  const Breed(id: '29', name: 'Basset Fauve De Bretagne'),
  const Breed(id: '30', name: 'Basset Hound'),
  const Breed(id: '31', name: 'Bavarian Mountain Scent Hound'),
  const Breed(id: '32', name: 'Beagle'),
  const Breed(id: '33', name: 'Beagle Harrier'),
  const Breed(id: '34', name: 'Bearded Collie'),
  const Breed(id: '35', name: 'Bedlington Terrier'),
  const Breed(id: '36', name: 'Belgian Shepherd'),
  const Breed(id: '37', name: 'Bergamasco Shepherd'),
  const Breed(id: '38', name: 'Berger De Beauce'),
  const Breed(id: '39', name: 'Bernese Mountain Dog'),
  const Breed(id: '40', name: 'Bichon Frise'),
  const Breed(id: '41', name: 'Billy'),
  const Breed(id: '42', name: 'Black And Tan Coonhound'),
  const Breed(id: '43', name: 'Bloodhound'),
  const Breed(id: '44', name: 'Blue Gascony Basset'),
  const Breed(id: '45', name: 'Blue Gascony Griffon'),
  const Breed(id: '46', name: 'Blue Picardy Spaniel'),
  const Breed(id: '47', name: 'Bohemian Shepherd'),
  const Breed(id: '48', name: 'Bohemian Wirehaired Pointing Griffon'),
  const Breed(id: '49', name: 'Bolognese'),
  const Breed(id: '50', name: 'Border Collie'),
  const Breed(id: '51', name: 'Border Terrier'),
  const Breed(id: '52', name: 'Borzoi'),
  const Breed(id: '53', name: 'Croatian Shepherd'),
  const Breed(id: '54', name: 'Barak'),
  const Breed(id: '55', name: 'Boston Terrier'),
  const Breed(id: '56', name: 'Bourbonnais Pointing Dog'),
  const Breed(id: '57', name: 'Bouvier Des Ardennes'),
  const Breed(id: '58', name: 'Bouvier Des Flandres'),
  const Breed(id: '59', name: 'Boxer'),
  const Breed(id: '60', name: 'Brazilian Terrier'),
  const Breed(id: '61', name: 'Brazilian Tracker'),
  const Breed(id: '62', name: 'Briard'),
  const Breed(id: '63', name: 'Briquet Griffon Vendeen'),
  const Breed(id: '64', name: 'Brittany Spaniel'),
  const Breed(id: '65', name: 'Broholmer'),
  const Breed(id: '66', name: 'Bull Terrier'),
  const Breed(id: '67', name: 'Bulldog'),
  const Breed(id: '68', name: 'Bullmastiff'),
  const Breed(id: '69', name: 'Burgos Pointing Dog'),
  const Breed(id: '70', name: 'Cairn Terrier'),
  const Breed(id: '71', name: 'Canaan Dog'),
  const Breed(id: '72', name: 'Canadian Eskimo Dog'),
  const Breed(id: '73', name: 'Canarian Warren Hound'),
  const Breed(id: '74', name: 'Castro Laboreiro Dog'),
  const Breed(id: '75', name: 'Catalan Sheepdog'),
  const Breed(id: '76', name: 'Caucasian Shepherd'),
  const Breed(id: '77', name: 'Cavalier King Charles Spaniel'),
  const Breed(id: '78', name: 'Central Asia Shepherd'),
  const Breed(id: '79', name: 'Cesky Terrier'),
  const Breed(id: '80', name: 'Chesapeake Bay Retriever'),
  const Breed(id: '81', name: 'Chihuahua'),
  const Breed(id: '82', name: 'Chinese Crested Dog'),
  const Breed(id: '83', name: 'Chow Chow'),
  const Breed(id: '84', name: 'Cimarrón Uruguayo'),
  const Breed(id: '85', name: 'Cirneco Dell\'Etna'),
  const Breed(id: '86', name: 'Clumber Spaniel'),
  const Breed(id: '87', name: 'Styrian Hound'),
  const Breed(id: '88', name: 'Collie Rough'),
  const Breed(id: '89', name: 'Collie Smooth'),
  const Breed(id: '90', name: 'Continental Bulldog'),
  const Breed(id: '91', name: 'Continental Toy Spaniel'),
  const Breed(id: '92', name: 'Coton De Tulear'),
  const Breed(id: '93', name: 'Croatian Shepherd'),
  const Breed(id: '94', name: 'Curly Coated Retriever'),
  const Breed(id: '95', name: 'Czechoslovakian Wolfdog'),
  const Breed(id: '96', name: 'Dachshund'),
  const Breed(id: '97', name: 'Dalmatian'),
  const Breed(id: '98', name: 'Dandie Dinmont Terrier'),
  const Breed(id: '99', name: 'Danish-Swedish Farmdog'),
  const Breed(id: '100', name: 'Deerhound'),
  const Breed(id: '101', name: 'Deutsch Langhaar'),
  const Breed(id: '102', name: 'Deutsch Stichelhaar'),
  const Breed(id: '103', name: 'Dobermann'),
  const Breed(id: '104', name: 'Dogo Argentino'),
  const Breed(id: '105', name: 'Dogue De Bordeaux'),
  const Breed(id: '106', name: 'Drentsche Partridge Dog'),
  const Breed(id: '107', name: 'Drever'),
  const Breed(id: '108', name: 'Dutch Schapendoes'),
  const Breed(id: '109', name: 'Dutch Shepherd'),
  const Breed(id: '110', name: 'Dutch Smoushond'),
  const Breed(id: '111', name: 'East Siberian Laika'),
  const Breed(id: '112', name: 'English Cocker Spaniel'),
  const Breed(id: '113', name: 'English Foxhound'),
  const Breed(id: '114', name: 'English Pointer'),
  const Breed(id: '115', name: 'English Setter'),
  const Breed(id: '116', name: 'English Springer Spaniel'),
  const Breed(id: '117', name: 'English Toy Terrier (Black &Tan)'),
  const Breed(id: '118', name: 'Entlebuch Cattle Dog'),
  const Breed(id: '119', name: 'Estonian Hound'),
  const Breed(id: '120', name: 'Estrela Mountain Dog'),
  const Breed(id: '121', name: 'Eurasian'),
  const Breed(id: '122', name: 'Fawn Brittany Griffon'),
  const Breed(id: '123', name: 'Field Spaniel'),
  const Breed(id: '124', name: 'Fila Brasileiro'),
  const Breed(id: '125', name: 'Finnish Hound'),
  const Breed(id: '126', name: 'Finnish Lapponian Dog'),
  const Breed(id: '127', name: 'Finnish Spitz'),
  const Breed(id: '128', name: 'Flat Coated Retriever'),
  const Breed(id: '129', name: 'Fox Terrier (Smooth)'),
  const Breed(id: '130', name: 'Fox Terrier (Wire)'),
  const Breed(id: '131', name: 'French Bulldog'),
  const Breed(id: '132', name: 'French Pointing Dog'),
  const Breed(id: '133', name: 'French Spaniel'),
  const Breed(id: '134', name: 'French Tricolour Hound'),
  const Breed(id: '135', name: 'French Water Dog'),
  const Breed(id: '136', name: 'French White & Black Hound'),
  const Breed(id: '137', name: 'French White And Orange Hound'),
  const Breed(id: '138', name: 'Frisian Water Dog'),
  const Breed(id: '139', name: 'Gascon Saintongeois'),
  const Breed(id: '140', name: 'German Hound'),
  const Breed(id: '141', name: 'German Hunting Terrier'),
  const Breed(id: '142', name: 'German Pinscher'),
  const Breed(id: '143', name: 'German Shepherd'),
  const Breed(id: '144', name: 'German Shorthaired Pointing Dog'),
  const Breed(id: '145', name: 'German Spaniel'),
  const Breed(id: '146', name: 'German Spitz'),
  const Breed(id: '147', name: 'German Wirehaired Pointing Dog'),
  const Breed(id: '148', name: 'Giant Schnauzer'),
  const Breed(id: '149', name: 'Golden Retriever'),
  const Breed(id: '150', name: 'Gordon Setter'),
  const Breed(id: '151', name: 'Grand Basset Griffon Vendeen'),
  const Breed(id: '152', name: 'Grand Griffon Vendeen'),
  const Breed(id: '153', name: 'Great Anglo-French Tricolour Hound'),
  const Breed(id: '154', name: 'Great Anglo-French White & Orange Hound'),
  const Breed(id: '155', name: 'Great Anglo-French White And Black Hound'),
  const Breed(id: '156', name: 'Great Dane'),
  const Breed(id: '157', name: 'Great Gascony Blue'),
  const Breed(id: '158', name: 'Great Swiss Mountain Dog'),
  const Breed(id: '159', name: 'Greenland Dog'),
  const Breed(id: '160', name: 'Greyhound'),
  const Breed(id: '161', name: 'Griffon Belge'),
  const Breed(id: '162', name: 'Griffon Bruxellois'),
  const Breed(id: '163', name: 'Griffon Nivernais'),
  const Breed(id: '164', name: 'Halden Hound'),
  const Breed(id: '165', name: 'Hamiltonstövare'),
  const Breed(id: '166', name: 'Hanoverian Scent Hound'),
  const Breed(id: '167', name: 'Harrier'),
  const Breed(id: '168', name: 'Havanese'),
  const Breed(id: '169', name: 'Hellenic Hound'),
  const Breed(id: '170', name: 'Hokkaido'),
  const Breed(id: '171', name: 'Hovawart'),
  const Breed(id: '172', name: 'Hungarian Greyhound'),
  const Breed(id: '173', name: 'Transylvanian Hound'),
  const Breed(id: '174', name: 'Vizsla'),
  const Breed(id: '175', name: 'Hungarian Wirehaired Pointer'),
  const Breed(id: '176', name: 'Hygen Hound'),
  const Breed(id: '177', name: 'Ibizan Podenco'),
  const Breed(id: '178', name: 'Icelandic Sheepdog'),
  const Breed(id: '179', name: 'Irish Glen Of Imaal Terrier'),
  const Breed(id: '180', name: 'Irish Red And White Setter'),
  const Breed(id: '181', name: 'Irish Red Setter'),
  const Breed(id: '182', name: 'Irish Soft Coated Wheaten Terrier'),
  const Breed(id: '183', name: 'Irish Terrier'),
  const Breed(id: '184', name: 'Irish Water Spaniel'),
  const Breed(id: '185', name: 'Irish Wolfhound'),
  const Breed(id: '186', name: 'Istrian Shorthaired Hound'),
  const Breed(id: '187', name: 'Istrian Wirehaired Hound'),
  const Breed(id: '188', name: 'Italian Cane Corso'),
  const Breed(id: '189', name: 'Italian Pointing Dog'),
  const Breed(id: '190', name: 'Italian Roughhaired Segugio'),
  const Breed(id: '191', name: 'Italian Shorthaired Segugio'),
  const Breed(id: '192', name: 'Italian Sighthound'),
  const Breed(id: '193', name: 'Italian Spinone'),
  const Breed(id: '194', name: 'Italian Volpino'),
  const Breed(id: '195', name: 'Jämthund'),
  const Breed(id: '196', name: 'Jack Russell Terrier'),
  const Breed(id: '197', name: 'Japanese Chin'),
  const Breed(id: '198', name: 'Japanese Spitz'),
  const Breed(id: '199', name: 'Japanese Terrier'),
  const Breed(id: '200', name: 'Kai'),
  const Breed(id: '201', name: 'Kangal Shepherd'),
  const Breed(id: '202', name: 'Karelian Bear Dog'),
  const Breed(id: '203', name: 'Karst Shepherd'),
  const Breed(id: '204', name: 'Kerry Blue Terrier'),
  const Breed(id: '205', name: 'King Charles Spaniel'),
  const Breed(id: '206', name: 'Kintamani-Bali Dog'),
  const Breed(id: '207', name: 'Kishu'),
  const Breed(id: '208', name: 'Kleiner Münsterländer'),
  const Breed(id: '209', name: 'Komondor'),
  const Breed(id: '210', name: 'Korea Jindo Dog'),
  const Breed(id: '211', name: 'Kromfohrländer'),
  const Breed(id: '212', name: 'Kuvasz'),
  const Breed(id: '213', name: 'Labrador Retriever'),
  const Breed(id: '214', name: 'Laika'),
  const Breed(id: '215', name: 'Lakeland Terrier'),
  const Breed(id: '216', name: 'Lancashire Heeler'),
  const Breed(id: '217', name: 'Landseer (European Continental Type)'),
  const Breed(id: '218', name: 'Lapponian Herder'),
  const Breed(id: '219', name: 'Large Munsterlander'),
  const Breed(id: '220', name: 'Leonberger'),
  const Breed(id: '221', name: 'Lhasa Apso'),
  const Breed(id: '222', name: 'Little Lion Dog'),
  const Breed(id: '223', name: 'Pyrenean Sheepdog'),
  const Breed(id: '224', name: 'Majorca Mastiff'),
  const Breed(id: '225', name: 'Majorca Shepherd'),
  const Breed(id: '226', name: 'Maltese'),
  const Breed(id: '227', name: 'Manchester Terrier'),
  const Breed(id: '228', name: 'Maremma And The Abruzzes Sheepdog'),
  const Breed(id: '229', name: 'Mastiff'),
  const Breed(id: '230', name: 'Anglo-French Hound'),
  const Breed(id: '231', name: 'Miniature American Shepherd'),
  const Breed(id: '232', name: 'Miniature Bull Terrier'),
  const Breed(id: '233', name: 'Miniature Pinscher'),
  const Breed(id: '234', name: 'Miniature Schnauzer'),
  const Breed(id: '235', name: 'Montenegrin Mountain Hound'),
  const Breed(id: '236', name: 'Mudi'),
  const Breed(id: '237', name: 'Neapolitan Mastiff'),
  const Breed(id: '238', name: 'Nederlandse Kooikerhondje'),
  const Breed(id: '239', name: 'Newfoundland'),
  const Breed(id: '240', name: 'Norfolk Terrier'),
  const Breed(id: '241', name: 'Norman Artesien Basset'),
  const Breed(id: '242', name: 'Norrbottenspitz'),
  const Breed(id: '243', name: 'Norwegian Buhund'),
  const Breed(id: '244', name: 'Norwegian Elkhound Black'),
  const Breed(id: '245', name: 'Norwegian Elkhound Grey'),
  const Breed(id: '246', name: 'Norwegian Hound'),
  const Breed(id: '247', name: 'Norwegian Lundehund'),
  const Breed(id: '248', name: 'Norwich Terrier'),
  const Breed(id: '249', name: 'Nova Scotia Duck Tolling Retriever'),
  const Breed(id: '250', name: 'Old Danish Pointing Dog'),
  const Breed(id: '251', name: 'Old English Sheepdog'),
  const Breed(id: '252', name: 'Otterhound'),
  const Breed(id: '253', name: 'Parson Russell Terrier'),
  const Breed(id: '254', name: 'Pekingese'),
  const Breed(id: '255', name: 'Peruvian Hairless Dog'),
  const Breed(id: '256', name: 'Petit Basset Griffon Vendeen'),
  const Breed(id: '257', name: 'Petit Brabançon'),
  const Breed(id: '258', name: 'Pharaoh Hound'),
  const Breed(id: '259', name: 'Picardy Sheepdog'),
  const Breed(id: '260', name: 'Picardy Spaniel'),
  const Breed(id: '261', name: 'Poitevin'),
  const Breed(id: '262', name: 'Polish Greyhound'),
  const Breed(id: '263', name: 'Polish Hound'),
  const Breed(id: '264', name: 'Polish Hunting Dog'),
  const Breed(id: '265', name: 'Polish Lowland Sheepdog'),
  const Breed(id: '266', name: 'Pont-Audemer Spaniel'),
  const Breed(id: '267', name: 'Poodle'),
  const Breed(id: '268', name: 'Porcelaine'),
  const Breed(id: '269', name: 'Portuguese Pointing Dog'),
  const Breed(id: '270', name: 'Portuguese Sheepdog'),
  const Breed(id: '271', name: 'Portuguese Podengo'),
  const Breed(id: '272', name: 'Portuguese Water Dog'),
  const Breed(id: '273', name: 'Posavatz Hound'),
  const Breed(id: '274', name: 'Prague Ratter'),
  const Breed(id: '275', name: 'Presa Canario'),
  const Breed(id: '276', name: 'Pudelpointer'),
  const Breed(id: '277', name: 'Pug'),
  const Breed(id: '278', name: 'Puli'),
  const Breed(id: '279', name: 'Pumi'),
  const Breed(id: '280', name: 'Pyrenean Mastiff'),
  const Breed(id: '281', name: 'Pyrenean Mountain Dog'),
  const Breed(id: '282', name: 'Pyrenean Sheepdog'),
  const Breed(id: '283', name: 'Rafeiro Of Alentejo'),
  const Breed(id: '284', name: 'Rhodesian Ridgeback'),
  const Breed(id: '285', name: 'Romagna Water Dog'),
  const Breed(id: '286', name: 'Romanian Bucovina Shepherd'),
  const Breed(id: '287', name: 'Romanian Carpathian Shepherd'),
  const Breed(id: '288', name: 'Romanian Mioritic Shepherd'),
  const Breed(id: '289', name: 'Rottweiler'),
  const Breed(id: '290', name: 'Russian Black Terrier'),
  const Breed(id: '291', name: 'Russian Toy'),
  const Breed(id: '292', name: 'Saarloos Wolfhond'),
  const Breed(id: '293', name: 'Saint Germain Pointer'),
  const Breed(id: '294', name: 'Saint Miguel Cattle Dog'),
  const Breed(id: '295', name: 'Saluki'),
  const Breed(id: '296', name: 'Samoyed'),
  const Breed(id: '297', name: 'Šarplaninac'),
  const Breed(id: '298', name: 'Schillerstövare'),
  const Breed(id: '299', name: 'Schipperke'),
  const Breed(id: '300', name: 'Schnauzer'),
  const Breed(id: '301', name: 'Scottish Terrier'),
  const Breed(id: '302', name: 'Sealyham Terrier'),
  const Breed(id: '303', name: 'Segugio Maremmano'),
  const Breed(id: '304', name: 'Serbian Hound'),
  const Breed(id: '305', name: 'Serbian Tricolour Hound'),
  const Breed(id: '306', name: 'Shar Pei'),
  const Breed(id: '307', name: 'Shetland Sheepdog'),
  const Breed(id: '308', name: 'Shiba'),
  const Breed(id: '309', name: 'Shih Tzu'),
  const Breed(id: '310', name: 'Shikoku'),
  const Breed(id: '311', name: 'Siberian Husky'),
  const Breed(id: '312', name: 'Skye Terrier'),
  const Breed(id: '313', name: 'Sloughi'),
  const Breed(id: '314', name: 'Slovakian Chuvach'),
  const Breed(id: '315', name: 'Slovakian Hound'),
  const Breed(id: '316', name: 'Smålandsstövare'),
  const Breed(id: '317', name: 'Small Blue Gascony'),
  const Breed(id: '318', name: 'Small Swiss Hound'),
  const Breed(id: '319', name: 'South Russian Shepherd'),
  const Breed(id: '320', name: 'Spanish Greyhound'),
  const Breed(id: '321', name: 'Spanish Hound'),
  const Breed(id: '322', name: 'Spanish Mastiff'),
  const Breed(id: '323', name: 'Spanish Water Dog'),
  const Breed(id: '324', name: 'St. Bernard'),
  const Breed(id: '325', name: 'Stabijhoun'),
  const Breed(id: '326', name: 'Staffordshire Bull Terrier'),
  const Breed(id: '327', name: 'Sussex Spaniel'),
  const Breed(id: '328', name: 'Swedish Lapphund'),
  const Breed(id: '329', name: 'Swedish Vallhund'),
  const Breed(id: '330', name: 'Swiss Hound'),
  const Breed(id: '331', name: 'Taiwan Dog'),
  const Breed(id: '332', name: 'Tatra Shepherd'),
  const Breed(id: '333', name: 'Thai Bangkaew Dog'),
  const Breed(id: '334', name: 'Thai Ridgeback Dog'),
  const Breed(id: '335', name: 'Tibetan Mastiff'),
  const Breed(id: '336', name: 'Tibetan Spaniel'),
  const Breed(id: '337', name: 'Tibetan Terrier'),
  const Breed(id: '338', name: 'Tornjack'),
  const Breed(id: '339', name: 'Tosa'),
  const Breed(id: '340', name: 'Transmontano Mastiff'),
  const Breed(id: '341', name: 'Tyrolean Hound'),
  const Breed(id: '342', name: 'Valencian Terrier'),
  const Breed(id: '343', name: 'Weimaraner'),
  const Breed(id: '344', name: 'Welsh Corgi (Cardigan)'),
  const Breed(id: '345', name: 'Welsh Corgi (Pembroke)'),
  const Breed(id: '346', name: 'Welsh Springer Spaniel'),
  const Breed(id: '347', name: 'Welsh Terrier'),
  const Breed(id: '348', name: 'West Highland White Terrier'),
  const Breed(id: '349', name: 'West Siberian Laika'),
  const Breed(id: '350', name: 'Westphalian Dachsbracke'),
  const Breed(id: '351', name: 'Whippet'),
  const Breed(id: '352', name: 'White Swiss Shepherd'),
  const Breed(id: '353', name: 'Wirehaired Pointing Griffon Korthals'),
  const Breed(id: '354', name: 'Wirehaired Slovakian Pointer'),
  const Breed(id: '355', name: 'Xoloitzcuintle'),
  const Breed(id: '356', name: 'Yakutian Laika'),
  const Breed(id: '357', name: 'Yorkshire Terrier'),
];
